src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsuarioRepository::class)]
#[UniqueEntity(fields: ['correo'], message: 'There is already an account with this correo')]
class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nombre;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $telefono;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $correo;

    #[ORM\Column(type: 'string', length: 255)]
    private $password;

    #[ORM\Column(type: 'string', nullable: true)]
    private $fecha_nacimiento;

    #[ORM\Column(type: 'date')]
    private $fecha_registro;

    #[ORM\ManyToOne(targetEntity: Rol::class, inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private $rol;

    #[ORM\OneToMany(mappedBy: 'autor', targetEntity: Ejercicio::class)]
    private $ejercicios;

    #[ORM\OneToMany(mappedBy: 'usuario', targetEntity: Entrenamiento::class, orphanRemoval: true)]
    private $entrens;

    #[ORM\Column(type: 'string', length: 255)]
    private $apellidos;

    /**
     * @ORM\Column(type="json")
     */
    #[ORM\Column(type: 'json')]
    private $roles = [];

    public function __construct()
    {
        $this->ejercicios = new ArrayCollection();
        $this->entrens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->correo;
    }

    public function setCorreo(string $correo): self
    {
        $this->correo = $correo;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFechaNacimiento(): ?string
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(string $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getFechaRegistro(): ?\DateTimeInterface
    {
        return $this->fecha_registro;
    }

    public function setFechaRegistro(\DateTimeInterface $fecha_registro): self
    {
        $this->fecha_registro = $fecha_registro;

        return $this;
    }

    public function getRol(): ?Rol
    {
        return $this->rol;
    }

    public function setRol(?Rol $rol): self
    {
        $this->rol = $rol;
        $this->setRoles($this->roles);

        return $this;
    }

    /**
     * @return Collection|Ejercicio[]
     */
    public function getEjercicios(): Collection
    {
        return $this->ejercicios;
    }

    public function addEjercicio(Ejercicio $ejercicio): self
    {
        if (!$this->ejercicios->contains($ejercicio)) {
            $this->ejercicios[] = $ejercicio;
            $ejercicio->setAutor($this);
        }

        return $this;
    }

    public function removeEjercicio(Ejercicio $ejercicio): self
    {
        if ($this->ejercicios->removeElement($ejercicio)) {
            // set the owning side to null (unless already changed)
            if ($ejercicio->getAutor() === $this) {
                $ejercicio->setAutor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Entrenamiento[]
     */
    public function getEntrens(): Collection
    {
        return $this->entrens;
    }

    public function addEntren(Entrenamiento $entren): self
    {
        if (!$this->entrens->contains($entren)) {
            $this->entrens[] = $entren;
            $entren->setUsuario($this);
        }

        return $this;
    }

    public function removeEntren(Entrenamiento $entren): self
    {
        if ($this->entrens->removeElement($entren)) {
            // set the owning side to null (unless already changed)
            if ($entren->getUsuario() === $this) {
                $entren->setUsuario(null);
            }
        }

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->correo;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @see UserInterface
     * TODO: CAMBIAR-HO PER A QUE AGAFE ROL DE L'ALRTA TABLA.
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        if(empty($roles)){
          $this->setRoles($roles);
          //$roles[] = "ROLE_USER";
        }
        if(!in_array('ROLE_USER', $roles)){
          array_push($roles, 'ROLE_USER');
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $rolD = $this->rol->getRol();
        $this->roles = $roles;
        array_push($this->roles, $rolD);

        return $this;
    }

}

src/Controller/UsuarioController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Usuario;
use App\Repository\UsuarioRepository;
use App\Repository\RolRepository;
use App\Form\RegistrationFormType;
use App\Form\ChangePasswordFormType;
use App\Form\UpdateUserFormType;
use App\Security\EmailVerifier;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class UsuarioController extends AbstractController
{

    private EmailVerifier $emailVerifier;

    public function __construct(EmailVerifier $emailVerifier)
    {
        $this->emailVerifier = $emailVerifier;
    }

    #[Route('/profile', name: 'profile_page')]
     public function profileAction(): Response
     {
       $this->denyAccessUnlessGranted('ROLE_USER');

         return $this->redirectToRoute('home_page');
     }

    #[Route('/register', name: 'app_register')]
    public function register(Request $request, RolRepository $rolRepository, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new Usuario();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // encode the plain password
            $user->setPassword(
            $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $user->setFechaRegistro(new \DateTime('@'.strtotime('now')));
            $rol = $rolRepository->findById(2);
            $user->setRol($rol[0]);

            $entityManager->persist($user);
            $entityManager->flush();

            // generate a signed url and email it to the user
          /*  $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('aasins97@gmail.com', 'Ana'))
                    ->to($user->getCorreo())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );*/
            // do anything else you need here, like send an email

            return $this->redirectToRoute('app_login');
        }

        return $this->render('usuario/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/verify/email', name: 'app_verify_email')]
    public function verifyUserEmail(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // validate email confirmation link, sets User::isVerified=true and persists
        try {
            $this->emailVerifier->handleEmailConfirmation($request, $this->getUser());
        } catch (VerifyEmailExceptionInterface $exception) {
            $this->addFlash('verify_email_error', $exception->getReason());

            return $this->redirectToRoute('app_register');
        }

        // @TODO Change the redirect on success and handle or remove the flash message in your templates
        $this->addFlash('success', 'Your email address has been verified.');

        return $this->redirectToRoute('app_register');
    }

    #[Route('/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils, EntityManagerInterface $entityManager): Response
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('usuario/login.html.twig', [
            //'controller_name' => 'LoginController',
            'last_username' => $lastUsername,
            'error'         => $error,
        ]);
    }

    #[Route('/logout', name: 'app_logout')]
    public function logout(): void
    {
      throw new \Exception('Don\'t forget to activate logout in security.yaml');
    }

    #[Route('/cambiarContra', name: 'app_changePass')]
    public function changePass(Request $request, UsuarioRepository $usuarioRepository, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
      //TODO --> llevaro per a olvide contraseña
      $this->denyAccessUnlessGranted('ROLE_USER');
      $user = $this->getUser();

      /*if ($this->getUser()) {
        $user = $this->getUser();
      }else {
        $user = new Usuario();
      }*/
      $form = $this->createForm(ChangePasswordFormType::class, $user);
      $form->handleRequest($request);

      if ($form->isSubmitted() && $form->isValid()) {
        // TODO -> olvidé mi contraseña
        /*  if(!$this->getUser())
          {
            $user = $entityManager->getRepository(Usuario::class)->findOneBy(['correo', $form->get('correo')->getData()]);
          }*/
          // encode the plain password
          $user->setPassword(
          $userPasswordHasher->hashPassword(
                  $user,
                  $form->get('plainPassword')->getData()
              )
          );
          $entityManager->flush();
          return $this->redirectToRoute('app_login');
      }

      return $this->render('usuario/cambiarContra.html.twig', [
          'changePasswordForm' => $form->createView(),
      ]);
    }

    #[Route('/actualizarDatos', name: 'app_updateUser')]
    public function updateUserAction(Request $request, UsuarioRepository $usuarioRepository, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
      //TODO --> llevaro per a olvide contraseña
      $this->denyAccessUnlessGranted('ROLE_USER');
      $user = $this->getUser();

      $form = $this->createForm(UpdateUserFormType::class, $user);
      $form->handleRequest($request);

      if ($form->isSubmitted() && $form->isValid()) {
        // TODO -> olvidé mi contraseña
          $entityManager->flush();
          return $this->redirectToRoute('profile_page');
      }

      return $this->render('usuario/actualizarDatos.html.twig', [
          'updateForm' => $form->createView(),
          'usuario' => $user
      ]);
    }
}

templates/usuario/actualizarDatos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mis datos{% endblock %}

{% block body %}
<section class="py-5">
  <div class="container px-5">
    <!-- Contact form-->
      <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
        <div class="text-center mb-5">
          <h1 class="fw-bolder">Hola {{ usuario.nombre }}:</h1>
          <p class="lead fw-normal text-muted mb-0">
            Aquí puedes actualizar tus datos personales, si deseas cambiar tu contraseña pulsa
            <a href="{{ path('app_changePass') }}">aquí.</a>
          </p>
        </div>
        <div class="row gx-5 justify-content-center">
          <div class="col-lg-8 col-xl-8">
            {{ form_start(updateForm) }}
                {{ form_row(updateForm.correo) }}
                {{ form_row(updateForm.nombre)}}
                {{ form_row(updateForm.apellidos) }}
                {{ form_row(updateForm.telefono, {
                    type: 'tel'
                }) }}
                {{ form_row(updateForm.fechaNacimiento, {
                    type: 'Date'
                }) }}
                <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Actualizar</button></div>
            {{ form_end(updateForm) }}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/usuario/cambiarContra.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cambiar contraseña{% endblock %}

{% block body %}
<section class="py-5">
  <div class="container px-5">
    <!-- Contact form-->
      <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
        <div class="text-center mb-5">
          <h1 class="fw-bolder">Cambiar contraseña:</h1>
        </div>
        <div class="row gx-5 justify-content-center">
          <div class="col-lg-8 col-xl-8">
            {{ form_start(changePasswordForm) }}
                {{ form_row(changePasswordForm.correo) }}
                {{ form_row(changePasswordForm.plainPassword, {
                    label: 'Escriba la nueva contraseña:'
                }) }}
                <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Cambiar contraseña</button></div>
            {{ form_end(changePasswordForm) }}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/usuario/confirmation_email.html.twig
<h1>Hi! Please confirm your email!</h1>

<p>
    Please confirm your email address by clicking the following link: <br><br>
    <a href="{{ signedUrl }}">Confirm my Email</a>.
    This link will expire in {{ expiresAtMessageKey|trans(expiresAtMessageData, 'VerifyEmailBundle') }}.
</p>

<p>
    Cheers!
</p>

templates/usuario/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Iniciar sesión
{% endblock %}

{% block body %}

  <section class="py-5">
      <div class="container px-5">
          <!-- Contact form-->
          <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
              <div class="text-center mb-5">
                  <h1 class="fw-bolder">Iniciar sesión</h1>
                  <p class="lead fw-normal text-muted mb-0">
                    ¿No estás registrado? Registrate pulsando
                    <a href="{{ path('app_register') }}">aquí.</a>
                  </p>

              </div>
              <div class="row gx-5 justify-content-center">
                  <div class="col-lg-8 col-xl-6">
                      <form action="{{ path('app_login') }}" method="post">
                          <!-- Name input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="username" type="text" name="_username" value="{{ last_username }}"/>
                              <label for="email">Correo: </label>
                          </div>
                          <!-- Phone number input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="password" type="password" name="_password"/>
                              <label for="password">Contraseña: </label>
                          </div>
                          <!-- Submit Button-->
                          <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Iniciar sesión</button></div>
                      </form>
                  </div>
              </div>
          </div>
  </section>

{% endblock %}

templates/usuario/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registrarse{% endblock %}

{% block body %}
<section class="py-5">
  <div class="container px-5">
    <!-- Contact form-->
      <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
        <div class="text-center mb-5">
          <h1 class="fw-bolder">Registro:</h1>
          <p style="color: red">Los elementos en rojo son obligatorios.</p>
          <p class="lead fw-normal text-muted mb-0">
            ¿Ya estás registrado? Inicia sesión pulsando
            <a href="{{ path('app_login') }}">aquí.</a>
          </p>
        </div>
        <div class="row gx-5 justify-content-center">
          <div class="col-lg-8 col-xl-8">
            {% for flash_error in app.flashes('verify_email_error') %}
                <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
            {% endfor %}

            {{ form_start(registrationForm) }}
                {{ form_row(registrationForm.nombre)}}
                {{ form_row(registrationForm.apellidos) }}
                {{ form_row(registrationForm.telefono, {
                    type: 'tel'
                }) }}
                {{ form_row(registrationForm.fechaNacimiento, {
                    type: 'Date'
                }) }}

                {{ form_row(registrationForm.correo) }}
                {{ form_row(registrationForm.plainPassword, {
                    label: 'Password'
                }) }}
                {{ form_row(registrationForm.agreeTerms) }}
                <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Crear cuenta nueva</button></div>
            {{ form_end(registrationForm) }}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}