src/Entity/Ejercicio.php
<?php

namespace App\Entity;

use App\Repository\EjercicioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EjercicioRepository::class)]
class Ejercicio
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nombre;

    #[ORM\Column(type: 'string', length: 255)]
    private $descripcion;

    #[ORM\ManyToOne(targetEntity: Usuario::class, inversedBy: 'ejercicios')]
    #[ORM\JoinColumn(nullable: true)]
    private $autor;

    #[ORM\Column(type: 'date')]
    private $fecha_creacion;

    #[ORM\Column(type: 'boolean')]
    private $revisado;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $aceptado;

    #[ORM\Column(type: 'boolean')]
    private $disponible;

    #[ORM\Column(type: 'string', length: 255)]
    private $documento;

    #[ORM\Column(type: 'string', length: 255)]
    private $imagen;

    #[ORM\Column(type: 'integer')]
    private $niveles_disponibles;

    #[ORM\OneToMany(mappedBy: 'ejercicio', targetEntity: Entrenamiento::class, orphanRemoval: true)]
    private $entrenamientos;

    #[ORM\Column(type: 'string', length: 1024, nullable: true)]
    private $instrucciones;

    #[ORM\Column(type: 'array', nullable: true)]
    private $documentosExtra = [];

    public function __construct()
    {
        $this->entrenamientos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getAutor(): ?Usuario
    {
        return $this->autor;
    }

    public function setAutor(?Usuario $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getRevisado(): ?bool
    {
        return $this->revisado;
    }

    public function setRevisado(bool $revisado): self
    {
        $this->revisado = $revisado;

        return $this;
    }

    public function getAceptado(): ?bool
    {
        return $this->aceptado;
    }

    public function setAceptado(?bool $aceptado): self
    {
        $this->aceptado = $aceptado;

        return $this;
    }

    public function getDisponible(): ?bool
    {
        return $this->disponible;
    }

    public function setDisponible(bool $disponible): self
    {
        $this->disponible = $disponible;

        return $this;
    }

    public function getDocumento(): ?string
    {
        return $this->documento;
    }

    public function setDocumento(string $documento): self
    {
        $this->documento = $documento;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getNivelesDisponibles(): ?int
    {
        return $this->niveles_disponibles;
    }

    public function setNivelesDisponibles(int $niveles_disponibles): self
    {
        $this->niveles_disponibles = $niveles_disponibles;

        return $this;
    }

    /**
     * @return Collection|Entrenamiento[]
     */
    public function getEntrenamientos(): Collection
    {
        return $this->entrenamientos;
    }

    public function addEntrenamiento(Entrenamiento $entrenamiento): self
    {
        if (!$this->entrenamientos->contains($entrenamiento)) {
            $this->entrenamientos[] = $entrenamiento;
            $entrenamiento->setEjercicio($this);
        }

        return $this;
    }

    public function removeEntrenamiento(Entrenamiento $entrenamiento): self
    {
        if ($this->entrenamientos->removeElement($entrenamiento)) {
            // set the owning side to null (unless already changed)
            if ($entrenamiento->getEjercicio() === $this) {
                $entrenamiento->setEjercicio(null);
            }
        }

        return $this;
    }

    public function getInstrucciones(): ?string
    {
        return $this->instrucciones;
    }

    public function setInstrucciones(?string $instrucciones): self
    {
        $this->instrucciones = $instrucciones;

        return $this;
    }

    public function getDocumentosExtra(): ?array
    {
        return $this->documentosExtra;
    }

    public function setDocumentosExtra(?array $documentosExtra): self
    {
        $this->documentosExtra = $documentosExtra;

        return $this;
    }
}

templates/frontal/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Contacto
{% endblock %}

{% block body %}

  <section class="py-5">
      <div class="container px-5">
          <!-- Contact form-->
          <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
              <div class="text-center mb-5">
                  <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                  <h1 class="fw-bolder">Contacta con nosotros</h1>
                  <p class="lead fw-normal text-muted mb-0">Ayudanos a mejorar:</p>
              </div>
              <div class="row gx-5 justify-content-center">
                  <div class="col-lg-8 col-xl-6">
                      <!-- * * * * * * * * * * * * * * *-->
                      <!-- * * SB Forms Contact Form * *-->
                      <!-- * * * * * * * * * * * * * * *-->

                      <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                          <!-- Name input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="name" type="text" placeholder="Nombre" required />
                              <label for="name">Nombre</label>
                              <div class="invalid-feedback" data-sb-feedback="name:required">Por favor, diganos su nombre</div>
                          </div>
                          <!-- Email address input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="email" type="email" placeholder="name@ejemplo.com" required />
                              <label for="email">Correo electrónico</label>
                              <div class="invalid-feedback" data-sb-feedback="email:required">Necesitamos saber su correo.</div>
                              <div class="invalid-feedback" data-sb-feedback="email:email">El correo no es valido.</div>
                          </div>
                          <!-- Phone number input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="phone" type="tel" placeholder="666 666 666"/>
                              <label for="phone">Número de teléfono</label>
                          </div>
                          <!-- Message input-->
                          <div class="form-floating mb-3">
                              <textarea class="form-control" id="message" type="text" placeholder="Escriba su mensaje..." style="height: 10rem" required></textarea>
                              <label for="message">Mensaje</label>
                              <div class="invalid-feedback" data-sb-feedback="message:required">Por favor, escriba un mensaje.</div>
                          </div>
                          <!-- REVISAR ESTO-->

                          <div class="d-none" id="submitSuccessMessage">
                              <div class="text-center mb-3">
                                  <div class="fw-bolder">Gracias por contactar con nosotros!</div>
                                <!--  To activate this form, sign up a
                                  <br />
                                  <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>-->
                              </div>
                          </div>
                          <!-- REVISAR ESTO-->

                          <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Algo salio mal, intentelo de nuevo más tarde.</div></div>
                          <!-- Submit Button-->
                          <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Enviar</button></div>
                      </form>
                  </div>
              </div>
          </div>
          <!-- Contact cards-->
          <div class="row gx-5 row-cols-2 row-cols-lg-4 py-5">
              <div class="col">
                  <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-facebook"></i></div>
                  <div class="h5 mb-2">Facebook</div>
                  <p class="text-muted mb-0">XXXXXXXXX</p>
              </div>
              <div class="col">
                  <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-instagram"></i></div>
                  <div class="h5">Instagram</div>
                  <p class="text-muted mb-0">XXXXXXX</p>
              </div>
              <div class="col">
                  <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-twitter"></i></div>
                  <div class="h5">Twitter</div>
                  <p class="text-muted mb-0">XXXXXXXX</p>
              </div>
              <div class="col">
                  <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-telegram"></i></div>
                  <div class="h5">Telegram</div>
                  <p class="text-muted mb-0">XXXXXXXX</p>
              </div>
          </div>
      </div>
  </section>

{% endblock %}

templates/frontal/entrenamientos.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Pagina de entrenamientos
{% endblock %}

{% block body %}
  <!-- Games preview section-->
  <section class="py-5" id="games">
      <div class="container px-5 my-5">
          <div class="row gx-5 justify-content-center">
              <div class="col-lg-8 col-xl-6">
                  <div class="text-center">
                      <h2 class="fw-bolder">Entrenamientos disponibles:</h2>
                      <p class="lead fw-normal text-muted mb-5"></p>
                  </div>
              </div>
          </div>
          <div class="row gx-5">

            {% for entrenamiento in entrenamientos %}
            <!--empieza tarjeta-->
                <div class="col-lg-4 mb-5">
                    <div class="card h-100 shadow border-0">
                        <img class="card-img-top" src="img/entrenamientos/{{entrenamiento.imagen}}" alt="Imagen portada entrenamiento" />
                        <div class="card-body p-4">
                            <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">{{entrenamiento.nombre}}</h5></a>
                            <p class="card-text mb-0">{{entrenamiento.descripcion}}</p>
                        </div>
                        <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                            <div class="d-flex align-items-end justify-content-between">
                                <div class="d-flex align-items-center">
                                    <div class="small">
                                        <div class="fw-bold">{{entrenamiento.autor.nombre}}</div>
                                        <div class="text-muted">{{entrenamiento.fechaCreacion|date('d-m-Y')}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              <!--Acaba tarjeta-->
            {% endfor %}
          </div>
      </div>
  </section>
{% endblock %}

templates/frontal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Inicio
{% endblock %}

{% block body %}
  <!-- Header-->
  <header class="bg-dark py-5">
      <div class="container px-5">
          <div class="row gx-5 align-items-center justify-content-center">
              <div class="col-lg-8 col-xl-7 col-xxl-6">
                  <div class="my-5 text-center text-xl-start">
                      <h1 class="display-5 fw-bolder text-white mb-2">¡Entrenemos la vista!</h1>
                      <p class="lead fw-normal text-white-50 mb-4">Crea y añade nuevos ejercicios visuales para ayudar a los demás.</p>
                      <p class="lead fw-normal text-white-50 mb-4">También... entrena tu vista mediante la colección de ejercicios disponibles.</p>
                      <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                          <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#games">Entrenar</a>
                          <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{{ path('newGame_page') }}">Crear ejercicio</a>
                          <a class="btn btn-outline-light btn-lg px-4" href="#features">Saber más</a>
                      </div>
                  </div>
              </div>
              <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="img/index_header.jpg" alt="Ordenador y gafas" /></div>
          </div>
      </div>
  </header>

  <!-- Features section-->
  <section class="py-5" id="features">
      <div class="container px-5 my-5">
          <div class="row gx-5">
              <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0">¡Registrate y empieza hoy mismo!</h2></div>
              <div class="col-lg-8">
                  <div class="row gx-5 row-cols-1 row-cols-md-2">
                      <div class="col mb-5 h-100">
                          <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-eye-fill"></i></div>
                          <h2 class="h5">Entrenamientos</h2>
                          <p class="mb-0">Disponemos de una gran colección de entrenamientos dinamicos para acabar con la monotonia.</p>
                      </div>
                      <div class="col mb-5 h-100">
                          <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-clock-fill"></i></div>
                          <h2 class="h5">Disponibilidad</h2>
                          <p class="mb-0">Realizalos donde y cuando quieras, con total libertad de horarios.</p>
                      </div>
                      <div class="col mb-5 mb-md-0 h-100">
                          <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-plus-square-fill"></i></div>
                          <h2 class="h5">Participa</h2>
                          <p class="mb-0">Crea y añade nuevos ejercicios mediante nuestro formulario, para contribuir a la gran colección disponible.</p>
                      </div>
                      <div class="col h-100">
                          <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-graph-up"></i></div>
                          <h2 class="h5">Evolución</h2>
                          <p class="mb-0">Consulta tus gráficas de evolución facilmente desde tu perfil de usuario.</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <!-- Games preview section-->
  <section class="py-5" id="games">
      <div class="container px-5 my-5">
          <div class="row gx-5 justify-content-center">
              <div class="col-lg-8 col-xl-6">
                  <div class="text-center">
                      <h2 class="fw-bolder">Nuestros ejercicios</h2>
                      <p class="lead fw-normal text-muted mb-5">Una pequeña selección de nuestros ejercicios disponibles:</p>
                      <p class="lead fw-normal text-muted mb-5"><a href="{{ path('games_page') }}">Ver más</a></p>

                  </div>
              </div>
          </div>
          <div class="row gx-5">
          {% for ejercicio in ejercicios %}
          <!--empieza tarjeta-->
              <div class="col-lg-4 mb-5">
                  <div class="card h-100 shadow border-0">
                      <img class="card-img-top" src="img/ejercicios/{{ejercicio.imagen}}" alt="Imagen portada ejercicio" />
                      <div class="card-body p-4">
                          <!--<a class="text-decoration-none link-dark stretched-link" href=""></a>-->
                          <h5 class="card-title mb-3">{{ejercicio.id}} - {{ejercicio.nombre}}</h5>
                          <p class="card-text mb-0">{{ejercicio.descripcion}}</p>
                      </div>
                      <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                          <div class="d-flex align-items-end justify-content-between">
                              <div class="d-flex align-items-center">
                                  <div class="small">
                                      <div class="fw-bold">{{ejercicio.autor.nombre}}</div>
                                      <div class="text-muted">{{ejercicio.fechaCreacion|date('d-m-Y')}}</div>
                                  </div>
                              </div>
                          </div>
                          <div class="d-grid"><a class="btn btn-primary" href="{{ path('entrenar_page', {id: ejercicio.id}) }}">Entrenar</a></div>
                      </div>
                  </div>
              </div>
            <!--Acaba tarjeta-->
          {% endfor %}
          </div>
      </div>
  </section>
{% endblock %}

templates/frontal/perfil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Pagina personal
{% endblock %}

{% block body %}
  <section class="py-5" id="cards">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Bienvenido antonio:</h2>
                    <p class="lead fw-normal text-muted mb-5"></p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
    <!--empieza tarjeta-->
        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0">
                <div class="card-body p-4" style="border-left: 10px solid #212529;" onclick="mostrar('datos')">
                    <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Datos Personales</h5></a>
                </div>
            </div>
        </div>
      <!--Acaba tarjeta-->
      <!--empieza tarjeta-->
          <div class="col-lg-4 mb-5">
              <div class="card h-100 shadow border-0">
                  <div class="card-body p-4" style="border-left: 10px solid #212529;">
                      <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Gráficas</h5></a>
                  </div>
              </div>
          </div>
        <!--Acaba tarjeta-->
        <!--empieza tarjeta-->
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <div class="card-body p-4" style="border-left: 10px solid #212529;">
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Cambiar contraseña</h5></a>
                    </div>
                </div>
            </div>
          <!--Acaba tarjeta-->
          <!--empieza tarjeta-->
              <div class="col-lg-4 mb-5">
                  <div class="card h-100 shadow border-0">
                      <div class="card-body p-4" style="border-left: 10px solid #212529;" onclick="mostrar('juegos')">
                          <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Mis juegos</h5></a>
                      </div>
                  </div>
              </div>
            <!--Acaba tarjeta-->

      </div>
  </div>
  </section>

  <section class="py-5" id="datos" style="display: none;">
  <p>datos</p>
  </section>
  <section class="py-5" id="juegos" style="display: none;">
  <p>datos</p>
  </section>


{% endblock %}

{% block javascripts %}
<!-- encara no funciona be-->
  <script type="text/javascript">
    function mostrar(id){
      document.getElementById(id).style='';
    }
  </script>
{% endblock %}