src/Entity/Entrenamiento.php
<?php

namespace App\Entity;

use App\Repository\EntrenamientoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrenamientoRepository::class)]
class Entrenamiento
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Usuario::class, inversedBy: 'entrens')]
    #[ORM\JoinColumn(nullable: false)]
    private $usuario;

    #[ORM\ManyToOne(targetEntity: Ejercicio::class, inversedBy: 'entrenamientos')]
    #[ORM\JoinColumn(nullable: false)]
    private $ejercicio;

    #[ORM\Column(type: 'date')]
    private $fecha;

    #[ORM\Column(type: 'integer')]
    private $puntuacion;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $nivel_alcanzado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getEjercicio(): ?Ejercicio
    {
        return $this->ejercicio;
    }

    public function setEjercicio(?Ejercicio $ejercicio): self
    {
        $this->ejercicio = $ejercicio;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getPuntuacion(): ?int
    {
        return $this->puntuacion;
    }

    public function setPuntuacion(int $puntuacion): self
    {
        $this->puntuacion = $puntuacion;

        return $this;
    }

    public function getNivelAlcanzado(): ?int
    {
        return $this->nivel_alcanzado;
    }

    public function setNivelAlcanzado(?int $nivel_alcanzado): self
    {
        $this->nivel_alcanzado = $nivel_alcanzado;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
      <title>{% block title %}{% endblock %}</title>

      <!-- Bootstrap icons-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

      {% block baseStyleSheet %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="favicon2.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
      {% endblock %}

      {% block stylesheets %} {% endblock %}
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
          <!-- Navigation-->
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container px-5">
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li class="nav-item"><a class="nav-link" href="{{ path('home_page') }}">Inicio</a></li>
                      <li class="nav-item"><a class="nav-link" href="{{ path('newGame_page') }}">Añadir ejercicio</a></li>
                      <li class="nav-item"><a class="nav-link" href="{{ path('games_page') }}">Entrenar</a></li>
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                          {% if is_granted('ROLE_ADMIN') %}
                          <li class="nav-item"><a class="nav-link" href="{{ path('gamesReview_page') }}">Revisar ejercicios</a></li>
                          {% endif %}
                          <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="{{ path('profile_page') }}" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-circle"></i></a>
                              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                  <li><a class="dropdown-item" href="{{ path('app_updateUser') }}">Datos personales</a></li>
                                  <li><a class="dropdown-item" href="{{ path('app_changePass') }}">Cambiar contraseña</a></li>
                                  <li><a class="dropdown-item" href="{{ path('graficas_page', {id: 0}) }}">Gráficas</a></li>
                                  <li><a class="dropdown-item" href="{{ path('myGames_page')}}">Mis ejercicios</a></li>
                                  <li><a class="dropdown-item" href="{{ path('app_logout') }}">Cerrar sesion </a></li>
                              </ul>
                          </li>
                        {% else %}
                          <li class="nav-item"><a class="nav-link" href="{{ path('app_login') }}"><i class="bi bi-person-circle"></i></a></li>
                        {% endif %}



                          <!--  <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>
                              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                  <li><a class="dropdown-item" href="#">Portfolio Overview</a></li>
                                  <li><a class="dropdown-item" href="#">Portfolio Item</a></li>
                              </ul>
                          </li>-->
                      </ul>
                  </div>
              </div>
          </nav>


        {% block body %}{% endblock %}


      </main>
      <!-- footer -->
      <footer class="bg-dark py-4 mt-auto">
          <div class="container px-5">
              <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                  <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>
                  <div class="col-auto">
                    <!--  <a class="link-light small" href="#!">Privacy</a>
                      <span class="text-white mx-1">&middot;</span>
                      <a class="link-light small" href="#!">Terms</a>
                      <span class="text-white mx-1">&middot;</span>-->
                      <a class="link-light small" href="{{ path('contact_page') }}">Contacto</a>
                  </div>
              </div>
          </div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/chart.js@latest/dist/Chart.min.js"></script>
      {% block baseJS %}
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
      {% endblock %}

      {% block javascripts %}{% endblock %}
    </body>
</html>

templates/entrenamiento.html.twig
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% block tips %}{% endblock %}
  <head>
    <link rel="stylesheet" href="/css/entrenamiento.css">
  {% block css %}{% endblock %}
    <meta charset="utf-8">
  <title>{% block title %}{{ejercicio.nombre}}{% endblock %}</title>
  </head>
  <body onload="load()">
      <div id="cabecera">
        <p id="titulo">{{ejercicio.nombre}}</p>
        <p>Nivel: <span id="nivel">{{entrenamiento.nivelAlcanzado|default(0)}}</span> - Puntos: <span id="puntos">{{entrenamiento.puntuacion|default(0)}}</span></p>
        <a onclick="empezarCero()" style="color:blue;">Volver a empezar</a>
        {% block cabecera %}{% endblock %}
      </div>
        {% block juego %}
        {% endblock %}
        <form class="" action="{{ path('app_guardarEntrenamiento') }}" method="post" id="botones">
          <input type="hidden" name="puntos" id="inputPuntos" value="{{entrenamiento.puntuacion|default(0)}}">
          <input type="hidden" name="nivel" id="inputNivel" value="{{entrenamiento.nivelAlcanzado|default(0)}}">
          <input type="hidden" name="ejercicio" value="{{ejercicio.id}}">
          <button type="submit" name="button" id="acabar">Acabar entrenamiento</button>
        </form>
        <div id="instruccionesDiv">
          <fieldset>
            <legend>Instrucciones del juego:</legend>
            <p>{{ejercicio.instrucciones}}</p>
          </fieldset>
        </div>
  </body>
  {% block funcionalidad %}{% endblock %}
  <script type="text/javascript">
    var canvas = document.getElementsByTagName('canvas');
    if (canvas.length > 0) {
      document.getElementById('botones').style.position = 'relative';
      document.getElementById('instruccionesDiv').style.position = 'relative';
    }
  </script>
</html>